options:
  config:
    type: string
    default: /etc/jmx_exporter/jmx_exporter.yaml
    description: |-
      The path to the jmx_exporter configuration yaml. For examples
      visit https://github.com/prometheus/jmx_exporter/tree/master/example_configs.
  public:
    type: boolean
    default: false
    description: |-
      Should the jmx exporter expose itself to the public network.